Create EQF.json
CredentialEngine/Schema-Development pull request #961
Opened 2024-11-06 01:19 UTC by siuc-nate

2024-11-07 18:18 UTC, mparsons-ce approved these changes

2024-11-12 10:22 UTC, philbarker requested changes
Please add :
ceterms:source and/or ceasn:sourceDocumentation to res:framework
ceterms:precedes and ceterms:precededBy to the ProgressionLevels

Consider adding:
asn:hasProgressionLevel to the Competencies referenced by facetedDescription
skos:inScheme and/or skos:topConceptOf to concepts in res:facets and res:acronyms


(edit: delete request to us conceptTerm as we replaced facetType with conceptTerm, so that change not needed)

2024-11-14 22:37 UTC, siuc-nate commented
Thanks. I made several updates based on your suggestions.

2024-11-19 11:59 UTC, philbarker approved these changes

2024-11-19 11:59 UTC, merged